### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by olivierobert** [manojpanchal90/nimbletest#3]
Hello Manoj  👋 , thank you for your effort on the code submission. I am Olivier at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

**Comment by olivierobert** [comment]
I have now completed the initial round of reviews. Many parts of the codebase remain in an incomplete stage. So, I have focused on the most critical points to make sure we can keep this process within the allotted time. 

Please share your feedback on the open issues to get the conversation going 🙏

**Comment by manojpanchal90** [comment]
@olivierobert  Thank you, Olivier, for reviewing the code. I've noted most of your comments, and they seem valid; they were oversights on my part. Unfortunately, I'm currently traveling without access to my laptop, so I'll begin addressing them tomorrow. I plan to work through each comment and will reach out to you for a follow-up review, aiming to conclude this process in the next 2-3 days.

**Comment by olivierobert** [comment]
@manojpanchal90 After reviewing your submission and your proposed timeline to complete the code review, we have decided not to continue this process further. Thank you for your efforts and interest in Nimble

**Comment by manojpanchal90** [comment]
@olivierobert : I assume that there might be further conversation on code so giving the timeline of 2-3 days else i will complete it today. If there are any further more iteration i will work tomorrow.

**Comment by olivierobert** [comment]
@manojpanchal90 There will be no further updates from our team since we have decided not to proceed with your application at this time. We hope you understand and thank you again for your efforts.
