### ISSUE TITLE
[Bug] UI views look squished

### ISSUE THREAD

**Issue by olivierobert** [manojpanchal90/nimbletest#5]
## Issue

All screens, even at standard zoom level, look incorrectly dimensioned:

![CleanShot 2566-11-28 at 20 40 24@2x](https://github.com/manojpanchal90/nimbletest/assets/696529/eb3bf1f1-7f19-4fd8-b8b2-5edaf1875fc2)

<img width="1107" alt="image" src="https://github.com/manojpanchal90/nimbletest/assets/696529/e3273da8-3e01-40be-8536-d444f825f6a7">

**Comment by manojpanchal90** [comment]
Bug is produced due to conflict of Bootstrap. Issue is resolved and PR is created. Here is commit of PR request https://github.com/manojpanchal90/nimbletest/pull/8/commits/a7f7abc67ebd3be65a77df4f7f1e17c6b846395f

**Comment by olivierobert** [comment]
The PR #8 contained changes beyond the initial issue 🙈 It is best to scope each PR to a single issue.
