### ISSUE TITLE
[Feature] Render the stored HTML in the UI

### ISSUE THREAD

**Issue by olivierobert** [manojpanchal90/nimbletest#6]
## Issue

While the Google search result content is stored in the database, users can only view the HTML as code. The page is not viewable as a rendered HTML view.

As a result, a user cannot verify if the scraping results are correct.

## Expected

The HTML content should be viewable on the application, e.g., there could be a view of the content on a new page or in a modal.

> [!NOTE]
> There is a bit of a challenge to render HTML content from another page. Hence it is an expected feature of the application.

**Comment by manojpanchal90** [comment]
As per your Suggestion, Feature is implemented.
